willayy/modularml

Makefile

Added basic makefile for configuring, compiling and running the main binary from the terminal.
Added a Makefile in the root of the project
Fixes issue 5

5 feature request basic makefile for compilation and running binaries

---

src/include/a_tensor_func.hpp

I just changed the name of the include to sync with changes i did on my branch
NA

FIX Change include name, i changed to be the correct one on my branch.

---

Makefile
src/include/a_data_loader.hpp

I added the abstract dataloader class which defines a load interface used in the coming concrete implementation of loading onnx models.
Implements #7

Add abstract DataLoader class

---

src/include/a_tensor.hpp

Changed snake_case methods to camelCase
NA

Fix snake case -> camel case

---

src/include/a_tensor.hpp
src/include/data.hpp
src/include/main.hpp

Simply switched from ifndef/define to pragma once for a_tensor.hpp, data.hpp and main.hpp.
Fixes/Implements #29

Fix invalid/Header files changed to pragma once

---

src/include/a_layer.hpp

Add abstract Layer class, a_layer.hpp
abstract Layer class.
Implements #[1]

Add abstract Layer class, a_layer.hpp

---

src/include/mml_TensorFunction_Swish.hpp
src/include/modularml
tests/test_mml_TensorFunction_ReLU.cpp
tests/test_mml_TensorFunction_Swish.cpp
tests/test_mml_TensorFunction_Tanh.cpp

Added mml_TensorFunction_Swish class as well as a test called `test_mml_TensorFunction_Swish.cpp` that tests the swish function. I'll just merge this one with the other tensorfunciton classes still awaiting final review.
Closes #66

Add mml_TensorFunction_Swish class

---

onnx_to_json.py

Added clear documentation on each node that is present in the AlexNet to help guide our implementation so we know exactly which argument which we get from the json file.
Closes #63

Add documentation and QOL to ONNX script

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/invalid.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/branch_police.yaml
.github/workflows/issue_police.yaml
.github/workflows/pr_police.yaml

Added GitHub action runners that enforce Issue, PR, and branch name rules.
Closes #102

Add Feature: pr police

---

CMakeLists.txt
src/include/a_onnx_gemm.hpp
src/include/globals.hpp
src/include/mml_gemm.hpp
src/include/mml_onnx_gemm.hpp
src/include/modularml
src/mml_gemm.tpp
src/mml_onnx_gemm.tpp
tests/test_mml_gemm.cpp
tests/test_mml_onnx_gemm.cpp

Created an ONNX wrapper for the gemm_mml model, which includes abstraction, added support for transposition in gemm, implemented tests for the new features, and made a minor fix for macOS (homebrew users) in CMakeLists.tests.
Closes #118

Fix Invalid: Formula uses a different formula than onnx

---

CMakeLists.txt
Makefile
src/ReLU_node.tpp
src/Swish_node.tpp
src/TanH_node.tpp
src/array_mml.tpp
src/gemm_node.tpp
src/include/ReLU_node.hpp
src/include/Swish_node.hpp
src/include/TanH_node.hpp
src/include/a_arithmetic_module.hpp
src/include/array_mml.hpp
src/include/gemm_node.hpp
src/include/globals.hpp
src/include/mml_arithmetic.hpp
src/include/tensor_utility.hpp
src/mml_arithmetic.tpp
src/tensor_utility.tpp
tests/test_nodes.cpp

Split up all classes into implementation and interface, i think it looks really nice tbh.
Closes #125

Update Feature: Refactored all classes than can be slit up into hpp / tpp

---

src/include/modularml
src/include/reshape_node.hpp
src/reshape_node.tpp
tests/test_nodes.cpp

Implemented the reshape node as specified in the onnx documentation along with a few test cases for it.
Closes #119

Add Feature: Reshape node

---

src/conv_node.tpp
src/include/conv_node.hpp

Add update parameters method which during forward updates the parameters that are infered from the input and weight tensor.

Fix Bug: Getting incorrect parameters based on input and weight tensor

---

src/include/profiler.hpp
src/profiler.cpp
tests/test_profiler.cpp

Adds a simple timing utility which can be used to profile multiple sections of code and report the time taken for those blocks to complete.
Closes #61

Add Feature: Timer utility

---

src/Gelu_node.tpp
src/include/Gelu_node.hpp
src/include/modularml
src/tensor_utility.tpp
tests/test_mml_tensor.cpp
tests/test_nodes.cpp

Add tensorfunction GeluNode
Closes #82

Add Feature: GeluNode

---

src/include/mml_LRN_node.hpp
src/include/mml_pooling_node.hpp
src/include/modularml
src/mml_LRN_node.tpp
tests/test_lrn_node.cpp

Add Feature: LRN Node

---

src/include/a_arithmetic_module.hpp
src/include/mml_arithmetic.hpp
src/mml_arithmetic.tpp
tests/test_mml_arithmetic.cpp

Added the ArgMax funciton to arithmetic along with a few tests for it.
Closes #163

Add Feature: ArgMax function

---

src/include/tensor_utility.hpp
src/tensor_utility.tpp
tests/test_tensor_utility.cpp

Added the Kaiming Uniform Distribution function that I used during the LeNet test. Also made some tests for the functions that are in tensor_utility. Also noticed another issue that needed a quick fix in the tensors are close functions whilst running the test.
Most of the code in this pull request ended up just being basic tests to get some more coverage for tensor_utility.
Closes #165

Add Feature: Kaiming Uniform Distribution function

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/invalid.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/issue_police.yaml
.github/workflows/pr_police.yaml

Changed the brackets from [] to angle brackets to make issue and pr police work
Closes #117
Closes #131

Fix Bug: Change bracket types in templates and police

---

src/backend/mml_parser.cpp
src/datastructures/mml_array.tpp
src/datastructures/mml_tensor.tpp
src/include/datastructures/a_tensor.hpp
src/include/datastructures/mml_tensor.hpp
src/include/modularml
src/include/nodes/matmul.hpp
src/include/nodes/transpose.hpp
src/nodes/matmul.cpp
src/nodes/transpose.cpp
tests/test_matmul_node.cpp
tests/test_transpose_node.cpp

To be able to parse Mateos LeNet we need these nodes
MatMul performs matrix multiplication using two input nodes
Transpose Node transposes an input tensor along multiple ranks
Closes #45 
Closes #207

Add Feature: MatMul & Transpose Nodes

---

README.md

Add instructions on how to install easily using CMake fetch content
NA

Update Feature README.md
